# Bitcoin.kn
# Site information
url: https://sharathdt.github.io
baseurl: /bitcoin
developer: webjeda

paginate: 6
paginate_path: /page:num/


# Plugins used by the website
plugins: 
    - jekyll-paginate